# Generated by Django 3.2.7 on 2021-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('EA', 'Earning'), ('EX', 'Expense')], default='AS', max_length=2),
        ),
    ]
