# Generated by Django 3.2.7 on 2021-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type_name',
            field=models.CharField(default=models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('EA', 'Earning'), ('EX', 'Expense')], default='AS', max_length=2), max_length=16),
        ),
    ]
