# Generated by Django 3.2.7 on 2021-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_account_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type_name',
            field=models.CharField(default='account_type', max_length=16),
        ),
    ]
