# Generated by Django 3.2.7 on 2021-09-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_account_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type_name',
        ),
    ]
