# Generated by Django 3.2.7 on 2021-09-19 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bookings',
            field=models.ManyToManyField(related_name='_api_account_bookings_+', through='api.Booking', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 19)),
        ),
    ]
