# Generated by Django 3.2.7 on 2021-09-20 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_booking_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('RE', 'Revenue'), ('EX', 'Expense')], default='AS', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 20)),
        ),
    ]
